services:
  web:
    build:
      context: ./docker/odoo
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "${ODOO_PORT}:8069"
      - "${CHAT_PORT}:8072"
    volumes:
      - ./etc:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - HOST=db
      - PORT=5432
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped
    
  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    restart: unless-stopped
